name: server-run-check

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main

jobs:
  check_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'current'

      - name: Install dependencies
        run: npm install

      - name: Run server
        run: node server.js