name: server-run-check

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main

jobs:
  check-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Start server and check
        run: |
        node server.js
        sleep 5 # Подождать несколько секунд для запуска сервера
        if curl --output /dev/null --silent --head --fail http://localhost:3000; then
          echo "Server is running"
        else
          echo "Server failed to start"
          exit 1
        fi
      - name: Stop server
      run: |
        kill $(lsof -t -i:3000) # Остановить сервер по порту 3000
