name: server-run-check

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main

jobs:
  check-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          npm install
      - name: Start server and check
        run: |
          node server.js &
          echo "Waiting for the server to start..."
          until curl -sSf http://localhost:3000; do
            echo "Server is not yet available. Retrying..."
            sleep 5
          done
          echo "Server is running."
      - name: Stop server
        run: |
          kill $(lsof -t -i:3000)
