name: server-run-check

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main

jobs:
  check-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Start server and check
        run: |
          node server.js
      - name: Stop server
        run: |
          kill $(lsof -t -i:3000)
